services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpwd
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - 8001:8978
    depends_on:
      - postgresql

volumes:
  postgresql_data:
