services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpwd
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpwd
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    environment:
      CB_DB_DRIVER: postgresql
      CB_DB_HOST: postgresql
      CB_DB_PORT: 5432
      CB_DB_DATABASE: db
      CB_DB_USERNAME: dbuser
      CB_DB_PASSWORD: dbpwd
    ports:
      - "8978:8978"
    depends_on:
      - postgresql
      - mariadb

volumes:
  postgresql_data:
  mariadb_data:
