services:
  # PHP + Apache
  php-apache: 
    container_name: php-apache
    build:
      dockerfile: Dockerfiles/PhpApache
    depends_on:
      - database
    volumes:
      - ./html:/var/www/html      # webserver document root folder
    ports:
      - 8000:80                   # accessible on port 8000

  # database
  database: 
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: univerzita
      MYSQL_USER: admin
      MYSQL_PASSWORD: heslo
    ports:
      - 9906:3306

  # database administration
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin  # base image
    ports:
      - 8080:80                   # accessible on port 8080
    environment:
      PMA_HOST: database
    depends_on:
      - database
